services:
  mysql-db:
    restart: always
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - micro-network

  eureka:
    restart: always
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - micro-network

  config-server:
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      CONFIG_SEARCH_LOCATIONS: file:/config-microservicios
    ports:
      - "8888:8888"
    volumes:
      - ./config-microservicios:/config-microservicios
    depends_on:
      - mysql-db
      - eureka
    networks:
      - micro-network

  cliente-service:
    restart: always
    build:
      context: ./cliente-service
      dockerfile: Dockerfile
    container_name: clientes
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_clientes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  mantencion-service:
    restart: always
    build:
      context: ./mantencion-service
      dockerfile: Dockerfile
    container_name: mantenciones
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_mantenciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  notificacion-service:
    restart: always
    build:
      context: ./notificacion-service
      dockerfile: Dockerfile
    container_name: notificaciones
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_notificaciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  pago-service:
    restart: always
    build:
      context: ./pago-service
      dockerfile: Dockerfile
    container_name: pagos
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_pagos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  reportes-service:
    restart: always
    build:
      context: ./reportes-service
      dockerfile: Dockerfile
    container_name: reportes
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_reportes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  seguro-service:
    restart: always
    build:
      context: ./seguro-service
      dockerfile: Dockerfile
    container_name: seguros
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_seguros
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  sucursal-service:
    restart: always
    build:
      context: ./sucursal-service
      dockerfile: Dockerfile
    container_name: sucursales
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_sucursales
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  vehiculo-service:
    restart: always
    build:
      context: ./vehiculo-service
      dockerfile: Dockerfile
    container_name: vehiculos
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/bd_vehiculos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - config-server
    networks:
      - micro-network

  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
    depends_on:
      - config-server
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge

volumes:
  mysql_data: