CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_mantenciones;
CREATE DATABASE IF NOT EXISTS bd_notificaciones;
CREATE DATABASE IF NOT EXISTS bd_pagos;
CREATE DATABASE IF NOT EXISTS bd_reportes;
CREATE DATABASE IF NOT EXISTS bd_seguros;
CREATE DATABASE IF NOT EXISTS bd_sucursales;
CREATE DATABASE IF NOT EXISTS bd_vehiculos;