server:
  port: 9090

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes
              uri: lb://cliente-service
              predicates:
                - Path=/api/v1/clientes/**, /v3/api-docs/clientes
              filters:
                - RewritePath=/v3/api-docs/clientes, /v3/api-docs
            - id: mantenciones
              uri: lb://mantencion-service
              predicates:
                - Path=/api/v1/mantenciones/**, /v3/api-docs/mantenciones
              filters:
                - RewritePath=/v3/api-docs/mantenciones, /v3/api-docs
            - id: notificaciones
              uri: lb://notificacion-service
              predicates:
                - Path=/api/v1/notificaciones/**, /v3/api-docs/notificaciones
              filters:
                - RewritePath=/v3/api-docs/notificaciones, /v3/api-docs
            - id: pagos
              uri: lb://pago-service
              predicates:
                - Path=/api/v1/pagos/**, /v3/api-docs/pagos
              filters:
                - RewritePath=/v3/api-docs/pagos, /v3/api-docs
            - id: reportes
              uri: lb://reportes-service
              predicates:
                - Path=/api/v1/reportes/**, /v3/api-docs/reportes
              filters:
                - RewritePath=/v3/api-docs/reportes, /v3/api-docs
            - id: seguros
              uri: lb://seguro-service
              predicates:
                - Path=/api/v1/seguros/**, /v3/api-docs/seguros
              filters:
                - RewritePath=/v3/api-docs/seguros, /v3/api-docs
            - id: sucursales
              uri: lb://sucursal-service
              predicates:
                - Path=/api/v1/sucursales/**, /v3/api-docs/sucursales
              filters:
                - RewritePath=/v3/api-docs/sucursales, /v3/api-docs
            - id: vehiculos
              uri: lb://vehiculo-service
              predicates:
                - Path=/api/v1/vehiculos/**, /v3/api-docs/vehiculos
              filters:
                - RewritePath=/v3/api-docs/vehiculos, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
    path: /swagger-ui.html
    urls:
      - name: clientes
        url: /v3/api-docs/clientes
      - name: mantenciones
        url: /v3/api-docs/mantenciones
      - name: notificaciones
        url: /v3/api-docs/notificaciones
      - name: pagos
        url: /v3/api-docs/pagos
      - name: reportes
        url: /v3/api-docs/reportes
      - name: seguros
        url: /v3/api-docs/seguros
      - name: sucursales
        url: /v3/api-docs/sucursales
      - name: vehiculos
        url: /v3/api-docs/vehiculos